# yaml-language-server: $schema=https://raw.githubusercontent.com/raineorshine/npm-check-updates/main/src/types/RunOptions.json
target: minor
reject:
  # Latest version doesn't work without major modifications.
  - "@vue/tsconfig"

