services:
  build:
    image: bridgecmdr/build
    build: .
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - '.:/project'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '$HOME/.Xauthority:/home/builder/.Xauthority:rw'
